### ISSUE TITLE
Provider errors

### ISSUE THREAD

**Issue by miigotu** [SickRage/sickrage-issues#164]
[ThePirateBay] :: Error while searching ThePirateBay, skipping: _do_search() got an unexpected keyword argument 'episode_count'

**Comment by MGaetan89** [comment]
I'll check every methods to make sure all named parameters are correct.

**Comment by miigotu** [comment]
is unused I think anyways.

**Comment by MGaetan89** [comment]
I got the same impression.
You're ok if I remove it if it is indeed unused?

**Comment by miigotu** [comment]
Yes, reducing the amount of arguments to _do_search is one of the steps in my refactor plan.

**Comment by MGaetan89** [comment]
I am almost done removing this argument. I will send a PR in a moment.
There were a couple other places where the named argument was wrong, so I fixed them as well.

**Comment by MGaetan89** [comment]
PR sent: https://github.com/SickRage/SickRage/pull/396

**Comment by duramato** [comment]
@MGaetan89 TVChaosUK titles dont get parsed
Before the change: 
```
2015-12-06 21:13:15 INFO     SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Unable to find a download for: [Red Rock - S01E72 - Episode 72]
2015-12-06 21:13:15 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: formatting pattern: %SN - S%0SE%0E - %EN -> Red Rock - S01E72 - Episode 72
2015-12-06 21:13:15 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: formatting pattern: %SN - S%0SE%0E - %EN -> Red Rock - S01E72 - Episode 72
2015-12-06 21:13:15 INFO     SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Ignoring result Red.Rock.S01E72.(3.Dec.2015).PDTV.mp4[IRL] because we don't want an episode that is Unknown
2015-12-06 21:13:15 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Don't want this quality, ignoring found episode
2015-12-06 21:13:15 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Any,Best = [ SDTV, SD DVD, 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ None ] Found = [ Unknown ]
2015-12-06 21:13:15 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Checking if found episode Red Rock S01E72 is wanted at quality Unknown
2015-12-06 21:13:15 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Parsed Red.Rock.S01E72.(3.Dec.2015).PDTV.mp4[IRL] into Red Rock - S01E72 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-12-06 21:13:14 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Search string: Red Rock - S01E72 
2015-12-06 21:13:14 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Found result: Red Rock S01E72 (3 Dec 2015) PDTV.mp4[IRL] 
2015-12-06 21:13:13 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Search string: Red Rock S01E72 
2015-12-06 21:13:13 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Search Mode: Episode
2015-12-06 21:13:11 INFO     SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Performing episode search for Red Rock
```

After:
```

2015-12-06 20:31:52 INFO     SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Unable to find a download for: [Red Rock - S01E72 - Episode 72]
2015-12-06 20:31:52 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: formatting pattern: %SN - S%0SE%0E - %EN -> Red Rock - S01E72 - Episode 72
2015-12-06 20:31:52 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: formatting pattern: %SN - S%0SE%0E - %EN -> Red Rock - S01E72 - Episode 72
2015-12-06 20:31:52 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Unable to parse the filename  into a valid show
2015-12-06 20:31:42 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Search string: Red Rock - S01E72 
2015-12-06 20:31:42 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Found result: Red Rock S01E72 (3 Dec 2015) PDTV.mp4[IRL]
2015-12-06 20:31:35 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Search string: Red Rock S01E72 
2015-12-06 20:31:35 DEBUG    SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Search Mode: Episode
2015-12-06 20:31:34 INFO     SEARCHQUEUE-MANUAL-289816 :: [TvChaosUK] :: Performing episode search for Red Rock
```

**Comment by duramato** [comment]
@MGaetan89 TVChaosUK isnt fixed ,so that you know

@SickRage/collaborators & @SickRage/moderators  Please use this thread for errors that where created by the providers rewrite

**Comment by MGaetan89** [comment]
Yes I know. You told me that in your PR.
